name: CHIP Tool API
version: "1.0.0"
slug: chip_tool_api
description: Expose Matter chip-tool via HTTP API
startup: application
boot: auto
init: false
ports:
  6000/tcp: 6000
host_network: true
homeassistant: 2023.0.0
arch:
  - amd64
  - aarch64
image: null
options: {}
schema: {}
